services:
  postgres:
    image: postgres:16-alpine
    container_name: mytask-postgres
    environment:
      POSTGRES_DB: mytask
      POSTGRES_USER: mytask
      POSTGRES_PASSWORD: mytask
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
